- name: Send URI to Telegram
  env:
    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    CHANNEL_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    V2RAY_WG_URI: ${{ env.v2ray_wg_uri }}
  run: |
    python -c "
    from telegram import Bot
    import os
    import logging

    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    logger = logging.getLogger(__name__)

    bot = Bot(token=os.getenv('TELEGRAM_BOT_TOKEN'))
    logger.info(f'Bot token: {os.getenv('TELEGRAM_BOT_TOKEN')}')
    logger.info(f'Channel ID: {os.getenv('CHANNEL_ID')}')
    logger.info(f'Message to send: New V2Ray WireGuard URI:\n{os.getenv('V2RAY_WG_URI')}')

    try:
        bot.send_message(chat_id=os.getenv('CHANNEL_ID'), text=f'New V2Ray WireGuard URI:\n{os.getenv('V2RAY_WG_URI')}')
        logger.info('Message sent successfully')
    except Exception as e:
        logger.error(f'Failed to send message: {str(e)}')
    "