name: Send WireGuard Config to Telegram

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:

jobs:
  send_wireguard_config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot==13.7

      - name: Generate and Send WireGuard Config
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python - << EOF
          import sys
          from telegram import Bot
          from telegram.error import TelegramError
          import json
          
          def generate_wireguard_config():
              # Example function; replace with actual WireGuard config generation logic
              config = {
                  "Interface": {
                      "PrivateKey": "your_private_key_here",
                      "Address": "10.0.0.2/24",
                      "DNS": "1.1.1.1"
                  },
                  "Peer": {
                      "PublicKey": "server_public_key",
                      "AllowedIPs": "0.0.0.0/0",
                      "Endpoint": "vpn.example.com:51820"
                  }
              }
              config_json = json.dumps(config, indent=2)
              config_url = "wireguard://example.com/config"  # Placeholder for URL
              return config_json, config_url

          config_json, config_url = generate_wireguard_config()
          
          bot = Bot(token=os.environ['TELEGRAM_BOT_TOKEN'])
          try:
              # Ensure that the chat_id is correctly formatted (should start with '-' for groups or channels)
              chat_id = os.environ['TELEGRAM_CHANNEL_ID']
              bot.send_message(chat_id=chat_id, text=f"Here's your new WireGuard config:\n\n```json\n{config_json}\n```", parse_mode='MarkdownV2')
              bot.send_message(chat_id=chat_id, text=f"WireGuard URL:\n{config_url}")
              print("Messages sent successfully to Telegram.")
          except TelegramError as e:
              print(f"An error occurred while sending messages: {e}")
          EOF