name: Get obfs4 Proxy and Send to Telegram

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  send_obfs4_proxy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 2: Install required libraries
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 3: Get obfs4 Proxy
      - name: Fetch obfs4 Proxy
        id: fetch_proxy
        run: |
          # Example: Fetching an obfs4 bridge (Replace with actual command to get your obfs4 proxy)
          obfs4_proxy=$(curl -s https://bridges.torproject.org/bridges?transport=obfs4 | grep -o "obfs4://[^ ]*" | head -n 1)
          echo "::set-output name=proxy::$obfs4_proxy"

      # Step 4: Send Proxy to Telegram
      - name: Send Proxy to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          proxy="${{ steps.fetch_proxy.outputs.proxy }}"
          if [ -z "$proxy" ]; then
            echo "No obfs4 proxy found."
            exit 1
          fi
          message="New obfs4 Proxy: $proxy"
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="$message"