name: WireGuard and V2Ray Automation

on:
  workflow_dispatch:

jobs:
  generate-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools python3-pip
        pip install pyrogram requests TgCrypto

    - name: Run Script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python3 script.py