name: Telegram Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # Run every 5 minutes
  workflow_dispatch:  # Add manual trigger

jobs:
  send_config:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python with a valid version (Python 3.9 in this case)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # Use Python 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run the bot script
      - name: Run Telegram bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python telegram_bot/bot.py