name: Get Tor Bridges and Send to Telegram

on:
  workflow_dispatch:

jobs:
  get-and-send-bridges:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get webtunnel bridges from Tor website
      run: |
        # Fetch bridges from Tor Bridges website
        response=$(curl -s --data "type=webtunnel" https://bridges.torproject.org/options)
        bridge1=$(echo "$response" | jq -r '.bridges[0]')
        bridge2=$(echo "$response" | jq -r '.bridges[1]')
        
        echo "Bridge 1: $bridge1"
        echo "Bridge 2: $bridge2"
        
        # Send bridges to Telegram
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="Here are your WebTunnel Bridges:\n1. $bridge1\n2. $bridge2"

    - name: Notify success
      run: echo "Bridges have been successfully sent to Telegram!"