name: Android CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 (required for Android projects)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step 3: Install Android SDK and dependencies
      - name: Set up Android SDK
        run: |
          echo "Setting up Android SDK"
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
          unzip commandlinetools-linux-6609375_latest.zip -d $HOME/Android/Sdk
          yes | $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager --licenses
          $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"

      # Step 4: Build the Android project
      - name: Build with Gradle
        run: ./gradlew build

      # Step 5: Run tests (optional)
      - name: Run Tests
        run: ./gradlew test

      # Step 6: Generate WireGuard configuration and send to Telegram
      - name: Generate WireGuard config and send to Telegram
        run: |
          # Generate WireGuard config (ensure you have the correct script or gradle task)
          CONFIG=$(./gradlew generateWireGuardConfig)

          # Ensure the WireGuard config is not empty
          if [ -z "$CONFIG" ]; then
            echo "WireGuard configuration generation failed."
            exit 1
          fi

          # Send the configuration to Telegram using Telegram Bot API
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=$CONFIG"
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}