name: Generate WireGuard Config and Notify

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"  # Run every 2 hours

jobs:
  generate-wireguard-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard qrencode git

      - name: Define Configuration Variables
        run: |
          # Define variables inline instead of using wg-gen.conf
          export wg_ip="10.0.0.1"
          export wg_port="51820"
          export wg_clients=5
          export wg_dns="8.8.8.8,8.8.4.4"
          export wg_endpoint="example.com"
          export wg_tunnel="full"
          export wg_users="user1,user2,user3,user4,user5"

          # Run the WireGuard generation script
          chmod +x scripts/wireguard-config.sh
          ./scripts/wireguard-config.sh

      - name: Compress Configuration Files
        run: |
          # Archive the generated configuration files
          tar -czvf configs.tar.gz /etc/wireguard/clients.d/

      - name: Send Configurations to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -F chat_id="$TELEGRAM_CHAT_ID" \
               -F document=@"configs.tar.gz" \
               "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendDocument"