name: Send obfs4 Bridges to Telegram

on:
  schedule:
    - cron: '0 0 * * *'  # This will run daily at midnight UTC, adjust as needed
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  send_bridges:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tor

    - name: Get obfs4 Bridges
      run: |
        echo "Getting obfs4 bridges..."
        # Here we simulate fetching the bridges; in reality, you'd use a proper method to get them
        bridges=$(echo "obfs4 91.134.80.167:11198 9F6651B7CA83B25D5C7BDC9E420210376199BCBE cert=ATSAxm7VszEv+BR+WoA7qQR0HhUb5wa8MgCr2lD7ZOBzx5DkjBrwHwrV4kZ3Y/APBUGbXQ iat-mode=0" | shuf -n 3)
        echo "Bridges fetched: $bridges"
        echo "BRIDGES=$bridges" >> $GITHUB_ENV

    - name: Send bridges to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Here are your obfs4 bridges for today:
          ```
          ${{ env.BRIDGES }}
          ```
          Use these to connect to Tor more securely.