name: Parse Endpoints and Select Random

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  schedule:
    - cron: "0 * * * *"  # Runs every 1 hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  parse-endpoints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download endpoints.md
        run: |
          # Replace this with the actual URL to your endpoints.md file
          curl -o endpoints.md https://raw.githubusercontent.com/Json-Script/engage.cloudflareclient.com/main/addPrt/Endpoint/IPV6/Irancell_TEST_V6_October222024.md

      - name: Parse and Select Random Endpoint
        id: select_endpoint
        run: |
          # Extract lines containing valid IP:PORT from the Markdown file
          ENDPOINTS=$(grep -Eo '[0-9a-fA-F:.]+:[0-9]+' endpoints.md)
          if [ -z "$ENDPOINTS" ]; then
            echo "No valid endpoints found in endpoints.md."
            exit 1
          fi
          # Display all endpoints (optional for debugging)
          echo "Extracted Endpoints:"
          echo "$ENDPOINTS"
          # Select a random endpoint
          RANDOM_ENDPOINT=$(echo "$ENDPOINTS" | shuf -n 1)
          echo "Selected Random Endpoint: $RANDOM_ENDPOINT"
          # Save the random endpoint to a GitHub Actions environment variable
          echo "ENDPOINT=$RANDOM_ENDPOINT" >> $GITHUB_ENV

      - name: Use Random Endpoint
        run: |
          # Use the selected endpoint
          echo "Using endpoint: $ENDPOINT"