name: Generate WireGuard Config

on:
  workflow_dispatch:

jobs:
  generate-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install WireGuard tools
      run: sudo apt-get update && sudo apt-get install -y wireguard-tools

    - name: Generate WireGuard keys
      id: gen-keys
      run: |
        # Set umask for security
        umask 077

        # Generate private and public keys
        wg genkey | tee privatekey | wg pubkey > publickey

        # Read keys into variables
        PRIVATE_KEY=$(cat privatekey)
        PUBLIC_KEY=$(cat publickey)

        # Export keys for later steps
        echo "PRIVATE_KEY=${PRIVATE_KEY}" >> $GITHUB_ENV
        echo "PUBLIC_KEY=${PUBLIC_KEY}" >> $GITHUB_ENV

    - name: Create WireGuard configuration
      id: create-config
      run: |
        # Define configuration variables
        PRIVATE_KEY="${{ env.PRIVATE_KEY }}"
        PUBLIC_KEY="${{ env.PUBLIC_KEY }}"
        PEER_PUBLIC_KEY="Replace_With_Peer_Public_Key" # Update with actual peer public key
        PEER_ENDPOINT="Replace_With_Peer_Endpoint"    # Update with actual peer endpoint

        # Create configuration
        cat > wg0.conf <<EOL
        [Interface]
        PrivateKey = $PRIVATE_KEY
        Address = 192.168.2.1/24
        ListenPort = 51820

        [Peer]
        PublicKey = $PEER_PUBLIC_KEY
        AllowedIPs = 192.168.2.2/32
        Endpoint = $PEER_ENDPOINT
        PersistentKeepalive = 25
        EOL

        # Display configuration
        cat wg0.conf
        
        # Base64 encode the configuration and remove newlines
        WIREGUARD_CONFIG=$(cat wg0.conf | base64 -w 0)
        echo "WIREGUARD_CONFIG=${WIREGUARD_CONFIG}" >> $GITHUB_ENV

    - name: Send configuration to Telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        # Decode configuration from base64
        CONFIG=$(echo "${{ env.WIREGUARD_CONFIG }}" | base64 --decode)

        # Send the configuration to Telegram
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="WireGuard Configuration:\n\n\`\`\`\n$CONFIG\n\`\`\`" \
          -d parse_mode=MarkdownV2