name: Generate WireGuard Config and Notify

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"  # Run every 2 hours

jobs:
  generate-wireguard-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard qrencode git

      - name: Make Script Executable
        run: chmod +x scripts/wireguard-config.sh

      - name: Generate WireGuard Configurations
        run: ./scripts/wireguard-config.sh

      - name: Compress Configuration Files
        run: |
          # Archive the generated configuration files
          tar -czvf configs.tar.gz /etc/wireguard/clients.d/

      - name: Send Configurations to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # Send the configuration archive to Telegram
          curl -F chat_id="$TELEGRAM_CHAT_ID" \
               -F document=@"configs.tar.gz" \
               "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendDocument"