name: Generate and Send WireGuard Config

on:
  schedule:
    - cron: "0 * * * *" # Run every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  generate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install WireGuard Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools

      - name: Fetch Markdown File
        run: curl -s -o endpoints.md https://raw.githubusercontent.com/Json-Script/engage.cloudflareclient.com/refs/heads/main/addPrt/Endpoint/IPV6/Irancell_TEST_V6_October222024.md

      - name: Parse Endpoints and Generate Config
        id: generate_config
        run: |
          # Extract the endpoint table and pick a random entry
          ENDPOINT=$(awk '/\| [0-9a-f]/ {print $2}' endpoints.md | shuf -n 1)
          PRIVATE_KEY=$(wg genkey)
          CONFIG="[Interface]
          Address = 192.168.17.97/24
          DNS = 8.8.8.8, 8.8.2.2
          PrivateKey = $PRIVATE_KEY

          [Peer]
          AllowedIPs = 0.0.0.0/0
          Endpoint = ${ENDPOINT}
          PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
          "
          echo "$CONFIG" > wireguard.conf
          echo "::set-output name=config::$CONFIG"

      - name: Send Config to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendDocument \
          -F chat_id=${TELEGRAM_CHAT_ID} \
          -F document=@wireguard.conf \
          -F caption="$(cat wireguard.conf)"