- name: Generate and Send WireGuard Config
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python - << EOF
          import sys
          from telegram import Bot
          from telegram.error import TelegramError

          # Mock implementation for demonstration purposes
          def generate_wireguard_config():
              return '{"key": "value"}', "https://example.com"

          print("Generating WireGuard configuration...")
          config_json, config_url = generate_wireguard_config()

          print(f"Generated Config JSON: {config_json}")
          print(f"Generated Config URL: {config_url}")

          bot = Bot(token="$TELEGRAM_BOT_TOKEN")
          print("Initialized Telegram Bot.")

          try:
              bot.send_message(
                  chat_id="$TELEGRAM_CHANNEL_ID",
                  text=f"WireGuard config:\n\n```json\n{config_json}\n```",
                  parse_mode="MarkdownV2"
              )
              print("Config JSON sent successfully.")
              
              bot.send_message(
                  chat_id="$TELEGRAM_CHANNEL_ID",
                  text=f"WireGuard URL: {config_url}"
              )
              print("Config URL sent successfully.")
          except TelegramError as e:
              print(f"TelegramError occurred: {e}")
          EOF