name: Send WireGuard Config to Telegram

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:

jobs:
  send_wireguard_config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Generate and Send WireGuard Config
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python - << EOF
          import sys
          from telegram import Bot
          from telegram.error import TelegramError
          import json

          sys.path.append('.')
          from script.py import generate_wireguard_config  # Adjust the path

          config_json, config_url = generate_wireguard_config()
          
          bot = Bot(token="$TELEGRAM_BOT_TOKEN")
          try:
              bot.send_message(chat_id="$TELEGRAM_CHANNEL_ID", text="Here's your new WireGuard config:\n\n```json\n" + config_json + "\n```")
              bot.send_message(chat_id="$TELEGRAM_CHANNEL_ID", text="WireGuard URL:\n" + config_url)
          except TelegramError as e:
              print(f"An error occurred: {e}")
          EOF