name: WireGuard Config Generation and Telegram Notification

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:

jobs:
  wireguard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up WireGuard dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools git qrencode

      - name: Set environment variables inline
        run: |
          export wg_ip="10.0.0.1"
          export wg_port="51820"
          export wg_clients=5
          export wg_dns="8.8.8.8,8.8.4.4"
          export wg_endpoint="example.com"
          export wg_tunnel="full"
          export wg_users="user1,user2,user3,user4,user5"

      - name: Run the WireGuard generation script
        run: |
          chmod +x scripts/wireguard-config.sh
          ./scripts/wireguard-config.sh

      - name: Archive the generated configuration files
        run: |
          tar -czvf configs.tar.gz /tmp/wireguard/clients.d/
        
      - name: Send result to Telegram
        run: |
          # Send the results of the generated WireGuard config to a Telegram bot/channel
          curl -X POST \
            -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -F document=@configs.tar.gz \
            -F caption="WireGuard config generated" \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument"