name: Generate and Send WireGuard Config

on:
  schedule:
    - cron: "0 * * * *" # Run every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  generate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools

      - name: Fetch Endpoints File
        run: |
          curl -sSL -o endpoints.md https://raw.githubusercontent.com/Json-Script/engage.cloudflareclient.com/main/addPrt/Endpoint/IPV6/Irancell_TEST_V6_October222024.md

      - name: Generate WireGuard Config
        id: generate_config
        run: |
          # Extract endpoint and pick one randomly
          ENDPOINT=$(awk '/\| [0-9a-f]/ {gsub(/^[ \t]+|[ \t]+$/,"",$2); print $2}' endpoints.md | shuf -n 1)

          # Generate keys
          PRIVATE_KEY=$(wg genkey)
          PUBLIC_KEY=$(echo "$PRIVATE_KEY" | wg pubkey)

          # Create WireGuard configuration file
          cat << EOF > wireguard.conf
[Interface]
Address = 172.16.0.2/32, 2606:4700:110:8c8f:b67f:3504:3651:7e61/128
DNS = 8.8.8.8, 8.8.4.4
PrivateKey = $PRIVATE_KEY

[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = $ENDPOINT
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
PersistentKeepalive = 25
EOF

          # Log for debugging (omit sensitive data)
          echo "Generated WireGuard configuration."
        env:
          CONFIG_PATH: wireguard.conf

      - name: Send WireGuard Config via Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendDocument" \
          -F chat_id=${TELEGRAM_CHAT_ID} \
          -F document=@${CONFIG_PATH} \
          -F caption="Generated WireGuard Config"