name: V2Ray WireGuard URI Generator and Telegram Notifier

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs every hour on the hour

jobs:
  generate_and_send:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools wireguard
        python -m pip install --upgrade pip
        pip install python-telegram-bot

    - name: Verify WireGuard installation
      run: |
        if ! command -v wg &> /dev/null; then
          echo "WireGuard not found!" >&2
          exit 1
        fi

    - name: Generate WireGuard URI
      id: generate_uri
      run: |
        private_key=$(wg genkey)
        public_key=$(echo "$private_key" | wg pubkey)
        private_key_encoded=$(echo -n "$private_key" | base64 | tr -d '\n')
        export V2RAY_WG_URI="wireguard://$public_key?$private_key_encoded"
        echo "v2ray_wg_uri=$V2RAY_WG_URI" >> $GITHUB_ENV

    - name: Send URI to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHANNEL_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        V2RAY_WG_URI: ${{ env.v2ray_wg_uri }}
      run: |
        python <<EOF
from telegram import Bot
import os

bot_token = os.getenv("TELEGRAM_BOT_TOKEN")
channel_id = os.getenv("CHANNEL_ID")
v2ray_wg_uri = os.getenv("V2RAY_WG_URI")

if not bot_token or not channel_id or not v2ray_wg_uri:
    raise ValueError("Missing required environment variables")

bot = Bot(token=bot_token)
bot.send_message(chat_id=channel_id, text=f"New V2Ray WireGuard URI:\n{v2ray_wg_uri}")
EOF