- name: Send to Telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.MY_CHAT_ID }}
      run: |
        # Read the files
        CONFIG_JSON=$(<config.json)
        CONFIG_URL=$(<config_url.txt)

        # Combine both messages
        MESSAGE="Generated WireGuard Config:\n\n\`\`\`\n${CONFIG_JSON}\n\`\`\`\n\nWireGuard URL:\n\n${CONFIG_URL}"

        # Send the combined message
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
          -d chat_id="${CHAT_ID}" \
          -d text="${MESSAGE}" \
          -d parse_mode="Markdown"