name: Generate WireGuard Config and Send to Telegram

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  generate_and_send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y wireguard-tools

    - name: Download Endpoint List
      run: |
        curl -o endpoints.md https://raw.githubusercontent.com/Json-Script/engage.cloudflareclient.com/main/addPrt/Endpoint/IPV6/Irancell_TEST_V6_October222024.md

    - name: Parse and Select Random Endpoint
      id: select_endpoint
      run: |
        # Extract lines containing IP:PORT from the Markdown file
        ENDPOINTS=$(grep -Eo '[0-9a-fA-F:]+\.[0-9]+$' endpoints.md)
        # Select a random endpoint
        RANDOM_ENDPOINT=$(echo "$ENDPOINTS" | shuf -n 1)
        echo "ENDPOINT=$RANDOM_ENDPOINT" >> $GITHUB_ENV
      shell: bash

    - name: Generate WireGuard Keys
      id: generate_keys
      run: |
        # Generate private and public keys
        wg genkey | tee privatekey | wg pubkey > publickey
        CLIENT_PRIVATE_KEY=$(cat privatekey)
        SERVER_PUBLIC_KEY="bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=" # Replace with actual server public key
        echo "PRIVATE_KEY=$CLIENT_PRIVATE_KEY" >> $GITHUB_ENV
        echo "SERVER_PUBLIC_KEY=$SERVER_PUBLIC_KEY" >> $GITHUB_ENV

    - name: Create WireGuard Configuration
      run: |
        cat <<EOF > client.conf
        [Interface]
        Address = 192.168.17.97/24
        DNS = 8.8.8.8, 8.8.4.4
        PrivateKey = ${{ env.PRIVATE_KEY }}

        [Peer]
        AllowedIPs = 0.0.0.0/0
        Endpoint = ${{ env.ENDPOINT }}
        PublicKey = ${{ env.SERVER_PUBLIC_KEY }}
        EOF
        echo "WireGuard configuration generated."

    - name: Send WireGuard Config to Telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -F chat_id=$TELEGRAM_CHAT_ID \
             -F document=@client.conf \
             -F caption="WireGuard Configuration with Endpoint: ${{ env.ENDPOINT }}" \
             https://api.telegram.org/bot$TELEGRAM_TOKEN/sendDocument