name: Generate WireGuard Config

on:
  workflow_dispatch:
    inputs:
      raw_file_url:
        description: "Raw file URL containing endpoints"
        required: true
        default: "https://raw.githubusercontent.com/your-repo/endpoints-file/main/endpoints.txt"

jobs:
  generate-config:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y wireguard-tools jq
        git clone https://github.com/ParamonPlay2205/wireguard-key-generator.git
        sudo sh wireguard-key-generator/gen_keys.sh
        sudo chmod 777 -R wireguard-key-generator/

    - name: Fetch endpoints
      run: |
        curl -s "${{ github.event.inputs.raw_file_url }}" > endpoints.txt
        endpoints=$(grep -oE '.*?:[0-9]+' endpoints.txt)
        random_endpoint=$(echo "$endpoints" | shuf -n 1)
        echo "::set-output name=endpoint::$random_endpoint"
      id: endpoints

    - name: Generate WireGuard keys
      run: |
        client_private_key=$(cat wireguard-key-generator/privatekey)
        client_public_key=$(cat wireguard-key-generator/publickey)
        echo "::set-output name=client_private_key::$client_private_key"
        echo "::set-output name=client_public_key::$client_public_key"
      id: keys

    - name: Create WireGuard config
      run: |
        echo "[Interface]
Address = 192.168.17.97/24
DNS = 8.8.8.8, 8.8.2.2
PrivateKey = ${{ steps.keys.outputs.client_private_key }}

[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = ${{ steps.endpoints.outputs.endpoint }}
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
" > client.conf
        echo "::set-output name=config_file::$(cat client.conf)"
      id: config

    - name: Send configuration via Telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendDocument" \
          -F chat_id="${TELEGRAM_CHAT_ID}" \
          -F document=@"client.conf" \
          -F caption="[Interface]
Address = 192.168.17.97/24
DNS = 8.8.8.8
PrivateKey = ${{ steps.keys.outputs.client_private_key }}

[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = ${{ steps.endpoints.outputs.endpoint }}
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="