name: WireGuard Config Sender

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows for manual triggering

jobs:
  send-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install WireGuard tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MANUAL_SEND: ${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }}
        run: |
          python main.py