name: Android CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 (required for Android projects)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step 3: Install Android SDK and dependencies
      - name: Set up Android SDK
        run: |
          echo "Setting up Android SDK"
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
          unzip commandlinetools-linux-6609375_latest.zip -d $HOME/Android/Sdk
          yes | $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager --licenses
          $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"

      # Step 4: Set up Gradle and build the project
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        run: ./gradlew build

      # Step 5: Run Tests (optional, depends on whether you have tests)
      - name: Run Tests
        run: ./gradlew test

      # Step 6: Generate WireGuard config and send it to Telegram
      - name: Generate WireGuard config and send to Telegram
        run: |
          # Generate the WireGuard config (This could be done with a script you write in your project)
          CONFIG=$(./gradlew generateWireGuardConfig)

          # Send the configuration to the Telegram channel
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=$CONFIG"
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}