name: V2Ray WireGuard URI Generator and Telegram Notifier

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs every hour on the hour

jobs:
  generate_and_send:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4 # Updated to the latest version of checkout action

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools
        if [ $? -ne 0 ]; then
          echo "Error: WireGuard installation failed."
          exit 1
        fi
        python3 -m pip install --upgrade pip
        pip3 install python-telegram-bot

    - name: Verify WireGuard installation
      run: |
        if ! command -v wg &> /dev/null; then
          echo "WireGuard not found"
          exit 1
        fi

    - name: Generate WireGuard URI
      id: generate_uri
      run: |
        wg genkey | tee privatekey | wg pubkey > publickey
        private_key=$(cat privatekey | base64 | tr -d '\n')
        public_key=$(cat publickey)
        echo "v2ray_wg_uri=wireguard://$public_key?$private_key" >> $GITHUB_OUTPUT

    - name: Send URI to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHANNEL_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        V2RAY_WG_URI: ${{ steps.generate_uri.outputs.v2ray_wg_uri }}
      run: |
        python3 -c "
        from telegram import Bot
        import os
        bot = Bot(token=os.getenv('TELEGRAM_BOT_TOKEN'))
        bot.send_message(chat_id=os.getenv('CHANNEL_ID'), text=f'New V2Ray WireGuard URI:\n{os.getenv(\"V2RAY_WG_URI\")}')
        "