name: WireGuard V2Ray URI Generation and Telegram Notification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_wireguard_config:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up WireGuard
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard

    - name: Generate WireGuard keys
      run: |
        umask 077
        wg genkey | tee privatekey | wg pubkey > publickey

    - name: Create WireGuard config
      run: |
        cat <<EOF > wg0.conf
        [Interface]
        PrivateKey = $(cat privatekey)
        Address = 172.16.0.2/32, 2606:4700:110:8df4:1e81:4e99:796e:9ea9/128

        [Peer]
        PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
        Endpoint = engage.cloudflareclient.com:2408
        AllowedIPs = 0.0.0.0/0, ::/0
        PersistentKeepalive = 25
        EOF

    - name: Create V2Ray WireGuard URI
      run: |
        private_key=$(cat privatekey)
        public_key=$(cat publickey)
        uri="wireguard://$(echo -n "$public_key" | base64 -w 0)%40engage.cloudflareclient.com:2408?address=172.16.0.2%2F32%2C2606%3A4700%3A110%3A8df4%3A1e81%3A4e99%3A796e%3A9ea9%2F128&presharedkey=&reserved=173%2C24%2C10&publickey=$(echo -n "$public_key" | base64 -w 0)&mtu=1280#Warp"
        echo "Generated V2Ray WireGuard URI: $uri" > uri.txt

    - name: Send URI to Telegram Channel
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        uri=$(cat uri.txt)
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d text="WireGuard V2Ray URI:\n$uri"