name: Send WireGuard Config to Telegram

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:

jobs:
  send_wireguard_config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Generate and Send WireGuard Config
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python - << EOF
          import sys
          from telegram import Bot
          from telegram.error import TelegramError

          sys.path.append('.')  # Ensure the script is accessible in the current directory
          from script import generate_wireguard_config  # Adjust path if script is in a subdirectory

          # Generate WireGuard configuration
          config_json, config_url = generate_wireguard_config()

          # Initialize bot
          bot = Bot(token="$TELEGRAM_BOT_TOKEN")
          try:
              # Send configuration as a JSON block
              bot.send_message(
                  chat_id="$TELEGRAM_CHANNEL_ID",
                  text=f"Here's your new WireGuard config:\n\n```json\n{config_json}\n```",
                  parse_mode="MarkdownV2"
              )
              # Send configuration URL
              bot.send_message(
                  chat_id="$TELEGRAM_CHANNEL_ID",
                  text=f"WireGuard URL:\n{config_url}"
              )
          except TelegramError as e:
              print(f"An error occurred: {e}")
          EOF