name: Generate WireGuard Config and Send via Telegram Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0
  workflow_dispatch:

jobs:
  generate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate WireGuard Config
        id: generate_config  # Assigning an ID to reference this step
        run: |
          # Fetch the raw file containing endpoints
          curl -s "${{ secrets.ENDPOINTS_URL }}" > endpoints.txt

          # Parse the endpoints file and select one random endpoint
          python - <<EOF
          import random
          import os
          
          with open('endpoints.txt', 'r') as file:
              lines = file.readlines()
          
          # Skipping the header
          endpoints = [line.split('|')[0].strip() for line in lines[1:] if line.strip()]
          
          if endpoints:
              selected_endpoint = random.choice(endpoints)
              print(f"Selected endpoint: {selected_endpoint}")

              # Write the selected endpoint to the output
              with open(os.environ['GITHUB_OUTPUT'], 'a') as output_file:
                  output_file.write(f"endpoint={selected_endpoint}\n")

              # Generate the WireGuard config
              with open('wg0.conf', 'w') as conf_file:
                  conf_file.write(f"""[Interface]
Address = 192.168.17.97/24
DNS = 8.8.8.8,8.8.2.2
PrivateKey = KDx7TXeCI2xGyyrS03pQTXtlFejbIcgvODPtAa3AElw=

[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = {selected_endpoint}
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1+SUtzH0JuVo51h2wPfgyo=
""")
          else:
              print("No endpoints found in the file!")
          EOF

      - name: Send Config via Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: wg0.conf
          caption: |
            Here is your hourly WireGuard configuration:

            ```
            [Interface]
            Address = 192.168.17.97/24
            DNS = 8.8.8.8
            PrivateKey = KDx7TXeCI2xGyyrS03pQTXtlFejbIcgvODPtAa3AElw=

            [Peer]
            AllowedIPs = 0.0.0.0/0
            Endpoint = ${{ steps.generate_config.outputs.endpoint }}
            PublicKey = bmXOC+F1FxEMF9dyiK2H5/1+SUtzH0JuVo51h2wPfgyo=
            ```