
name: V2Ray WireGuard URI Generator and Telegram Notifier

on:
  workflow_workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs every hour on the hour

jobs:
  generate_and_send:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot wireguard-tools

    - name: Generate WireGuard URI
      id: generate_uri
      run: |
        # Generate WireGuard keys and configuration
        wg genkey | tee privatekey | wg pubkey > publickey
        echo "wg_uri=$(cat privatekey | base64 | tr -d '\n')" >> $GITHUB_ENV
        # Here you would typically create a more complex WireGuard config, but for simplicity:
        echo "v2ray_wg_uri=wireguard://$(cat publickey)?$(cat privatekey | base64 | tr -d '\n')" >> $GITHUB_ENV

    - name: Send URI to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHANNEL_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        V2RAY_WG_URI: ${{ env.v2ray_wg_uri }}
      run: |
        python -c "from telegram import Bot; bot = Bot('$TELEGRAM_BOT_TOKEN'); bot.send_message(chat_id='$CHANNEL_ID', text='New V2Ray WireGuard URI:\n$V2RAY_WG_URI')"