name: Generate WireGuard Config

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Manual trigger

jobs:
  generate-config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install WireGuard Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools

    - name: Clone WireGuard Key Generator
      run: |
        git clone https://github.com/ParamonPlay2205/wireguard-key-generator.git
        cd wireguard-key-generator
        sudo sh gen_keys.sh
        mv privatekey private_key.txt
        mv publickey public_key.txt

    - name: Fetch Endpoint List
      run: |
        curl -s https://raw.githubusercontent.com/Json-Script/engage.cloudflareclient.com/refs/heads/main/addPrt/Endpoint/IPV6/Irancell_TEST_V6_October222024.md -o endpoints.md

    - name: Select Random Endpoint
      id: select-endpoint
      run: |
        ENDPOINT=$(grep -Eo '.*:[0-9]+' endpoints.md | shuf -n 1)
        echo "endpoint=${ENDPOINT}" >> $GITHUB_ENV

    - name: Generate WireGuard Config
      id: generate-config
      run: |
        PRIVATE_KEY=$(cat wireguard-key-generator/private_key.txt)
        PUBLIC_KEY="bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=" # Provided public key
        DNS="8.8.8.8, 8.8.2.2"
        ENDPOINT="${{ env.endpoint }}"
        cat <<EOF > wireguard-client.conf
        [Interface]
        Address = 192.168.17.97/24
        DNS = $DNS
        PrivateKey = $PRIVATE_KEY

        [Peer]
        AllowedIPs = 0.0.0.0/0
        Endpoint = $ENDPOINT
        PublicKey = $PUBLIC_KEY
EOF

    - name: Send Config to Telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -F document=@wireguard-client.conf \
             -F caption="[Interface]\nAddress = 192.168.17.97/24\nDNS = 8.8.8.8\nPrivateKey = (hidden for security)\n\n[Peer]\nAllowedIPs = 0.0.0.0/0\nEndpoint = ${{ env.endpoint }}\nPublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=" \
             "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}"