name: Generate WireGuard Config and Notify

on:
  schedule:
    - cron: "0 */2 * * *"  # Run every 2 hours

jobs:
  generate-wireguard-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard qrencode git

      - name: Generate WireGuard Configurations
        run: |
          # Set up WireGuard variables
          export wg_root='/etc/wireguard'
          export wg_client_dir="${wg_root}/clients.d"
          export wg_repo_dir="${wg_root}/repo.d"
          
          # Ensure directories exist
          mkdir -p "${wg_client_dir}"
          mkdir -p "${wg_repo_dir}"

          # Your WireGuard script logic here
          chmod +x ./path/to/your-script.sh
          ./path/to/your-script.sh

      - name: Compress Configuration Files
        run: |
          # Archive the generated configuration files
          tar -czvf configs.tar.gz /etc/wireguard/clients.d/

      - name: Send Configurations to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # Send the configuration archive to Telegram
          curl -F chat_id="$TELEGRAM_CHAT_ID" \
               -F document=@"configs.tar.gz" \
               "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendDocument"