name: Generate WireGuard Config and Notify

on:
  workflow_dispatch:
    inputs:
      peers_count:
        description: "Number of peers to generate"
        required: true
        default: 1

jobs:
  generate-wireguard-config:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools

    - name: Generate WireGuard keys
      id: generate_keys
      run: |
        # Generate the server private and public keys
        SERVER_PRIVATE_KEY=$(wg genkey)
        SERVER_PUBLIC_KEY=$(echo $SERVER_PRIVATE_KEY | wg pubkey)

        # Save server keys for use in the config
        echo "Server Private Key: $SERVER_PRIVATE_KEY"
        echo "$SERVER_PRIVATE_KEY" > privatekey
        echo "$SERVER_PUBLIC_KEY" > publickey

        # Generate a random port (use a default one if not specified)
        LISTEN_PORT="51820"

    - name: Generate WireGuard configuration
      id: generate_config
      run: |
        # Load the server's keys from the previous step
        SERVER_PRIVATE_KEY=$(cat privatekey)
        SERVER_PUBLIC_KEY=$(cat publickey)

        # Server IP and the number of peers
        SERVER_IP="10.0.0.1"
        PEERS_COUNT=${{ github.event.inputs.peers_count }}

        # Start the WireGuard server configuration
        WG_CONFIG="[Interface]
PrivateKey = $SERVER_PRIVATE_KEY
Address = $SERVER_IP/24
ListenPort = $LISTEN_PORT
"

        # Generate peer configurations
        for ((i=1; i<=PEERS_COUNT; i++))
        do
          PEER_PRIVATE_KEY=$(wg genkey)
          PEER_PUBLIC_KEY=$(echo $PEER_PRIVATE_KEY | wg pubkey)
          PEER_IP="10.0.0.$((i+1))"

          # Add peer to server configuration
          WG_CONFIG+="
[Peer]
PublicKey = $PEER_PUBLIC_KEY
AllowedIPs = $PEER_IP/32
Endpoint = engage.cloudflareclient.com:2408
PersistentKeepalive = 25
"

          # Create a peer configuration file
          echo "[Interface]
PrivateKey = $PEER_PRIVATE_KEY
Address = $PEER_IP/24

[Peer]
PublicKey = $SERVER_PUBLIC_KEY
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = engage.cloudflareclient.com:2408
PersistentKeepalive = 25
" > peer-$i.conf
        done

        # Save the generated server configuration
        echo "$WG_CONFIG" > wireguard.conf

    - name: Show server configuration
      run: cat wireguard.conf

    - name: Send configuration to Telegram
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d text="WireGuard Server Configuration:\n\n$(cat wireguard.conf)"

    - name: Upload peer configurations
      uses: actions/upload-artifact@v3
      with:
        name: peer-configs
        path: peer-*.conf